version: '3.8'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - ANSIBLE_FORCE_COLOR=true
    volumes:
      - ./terraform:/app/terraform
      - ./ansible:/app/ansible
      - ./badblood:/app/badblood
    command: ["python3", "exploit_forge.py"]
