- name: Create a temporary directory
  ansible.windows.win_tempfile:
    state: directory
  register: temp_dir

- name: Upload BadBlood
  ansible.windows.win_copy:
    src: "{{ playbook_dir }}/../badblood/"
    dest: "{{ temp_dir.path }}"

- name: Execute BadBlood script
  ansible.windows.win_shell: |
    {{ temp_dir.path }}/Invoke-BadBlood.ps1 -NonInteractive `
    -UserCount {{ user_count }} `
    -GroupCount {{ group_count }} `
    -ComputerCount {{ computer_count }}
  register: result

- name: Print BadBlood output
  ansible.builtin.debug:
    msg: "{{ result.stdout }}"

- name: Delete submodule from remote machine
  ansible.windows.win_file:
    path: "{{ temp_dir.path }}"
    state: absent
