- name: Set DN path
  set_fact:
    dn_path: "{{ (dn_path | default('')) + 'DC=' + item + (',' if ansible_loop.last == false else '') }}"
  loop: "{{ domain_name.split('.') }}"
  loop_control:
    extended: true
# - name: print dn_path
#   debug:
#     var: dn_path

