---
- name: Change the hostname to sample-hostname
  win_hostname:
    name: "{{ primary_domain_controller }}"
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: install active directory
  win_domain:
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios_domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    # pre_reboot_delay: 15
  when: ad.changed


