- name: install active directory
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    domain_netbios_name: "{{ netbios_domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
  when: ad.changed
