---
- name: Create OU for Staff
  microsoft.ad.ou:
    name: "Staff"
    path: "{{ dn_path }}"

- name: Create Employee account John
  microsoft.ad.user:
    name: John
    firstname: John
    surname: Doe
    password: Password123!
    state: present
    path: "ou=Staff,{{ dn_path }}"
    groups:
      set:
        - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create Employee account Sadie
  microsoft.ad.user:
    name: Sadie
    firstname: Sadie
    surname: Smith
    password: Password123!
    state: present
    path: "ou=Staff,{{ dn_path }}"
    groups:
      set:
        - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
