- name: Install active directory certificate services
  ansible.windows.win_feature:
    name: Adcs-Cert-Authority
    include_management_tools: true
  notify:
    - Install Certificate Authority

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install ADCSTemplate module
  community.windows.win_psmodule:
    name: ADCSTemplate
    accept_license: true
    force: true
    state: present

- name: Create and publish ADCS template
  ansible.windows.win_shell: |
    $json = "{{ lookup('file', './' + item + '.json') | from_json }}"
    New-ADCSTemplate -DisplayName "{{ item }}" -JSON $json -Publish
    Set-ADCSTemplateACL -DisplayName "{{ item }}" -Enroll -Identity "Authenticated Users", "Domain Users"
  with_items:
    - "ESC1"
    - "ESC2"
    - "ESC3"
    - "ESC4"

- name: Add write Permissions to ESC4
  ansible.windows.win_shell: |
    $Server = (Get-ADDomainController -Discover -ForceDiscover -Writable).HostName[0]
    $TemplateDisplayName = (Get-ADCSTemplate -DisplayName 'ESC4' -Server $Server).DistinguishedName
    $TemplatePath = 'AD:\{0}' -f $TemplateDisplayName
    $acl = Get-ACL $TemplatePath
    $account = New-Object System.Security.Principal.NTAccount("Authenticated Users")
    $sid = $account.Translate([System.Security.Principal.SecurityIdentifier])
    $ObjectType = [GUID]"00000000-0000-0000-0000-000000000000"
    $InheritedObjectType = [GUID]"00000000-0000-0000-0000-000000000000"
    $ace = New-Object System.DirectoryServices.ActiveDirectoryAccessRule $sid, 917684, 'Allow', $ObjectType, 'None', $InheritedObjectType
    $acl.AddAccessRule($ace)
    Set-ACL $TemplatePath -AclObject $acl
