- name: install active directory certificate services
  win_feature:
    name: Adcs-Cert-Authority
    include_management_tools: true
    notify: reboot

- name: install adcs certification authority
  win_shell: Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -Force
  notify: reboot

