- name: Install active directory certificate services
  ansible.windows.win_feature:
    name: Adcs-Cert-Authority
    include_management_tools: true
  notify: Install Certificate Authority

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure the required NuGet package provider version is installed
  ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

- name: Install ADCSTemplate module
  community.windows.win_psmodule:
    name: ADCSTemplate
    accept_license: true
    force: true
    state: present

- name: Read template names from file
  ansible.builtin.set_fact:
    template_names: "{{ lookup('file', 'template_names.txt').splitlines() }}"

- name: Select random template names
  ansible.builtin.set_fact:
    random_templates: "{{ random_templates | default([]) + [template_names | random] }}"
  loop: "{{ range(0, 4) | list }}"

- name: Define escalation list
  ansible.builtin.set_fact:
    escalation_list: ["ESC1", "ESC2", "ESC3", "ESC4"]

- name: Create and publish ADCS template
  ansible.windows.win_shell: |
    $json = "{{ lookup('file', './' + item.0 + '.json') | from_json }}"
    New-ADCSTemplate -DisplayName "{{ item.1 }}" -JSON $json -Publish
    Set-ADCSTemplateACL -DisplayName "{{ item.1 }}" -Enroll -Identity "Authenticated Users", "Domain Users"
  loop: "{{ escalation_list | zip(random_templates) | list }}"
  register: esc4

- name: Add write Permissions to ESC4
  ansible.windows.win_shell: |
    $Server = (Get-ADDomainController -Discover -ForceDiscover -Writable).HostName[0]
    $TemplateDisplayName = (Get-ADCSTemplate -DisplayName {{ esc4.results.3.item.1 }} -Server $Server).DistinguishedName
    $TemplatePath = 'AD:\{0}' -f $TemplateDisplayName
    $acl = Get-ACL $TemplatePath
    $account = New-Object System.Security.Principal.NTAccount("Authenticated Users")
    $sid = $account.Translate([System.Security.Principal.SecurityIdentifier])
    $ObjectType = [GUID]"00000000-0000-0000-0000-000000000000"
    $InheritedObjectType = [GUID]"00000000-0000-0000-0000-000000000000"
    $ace = New-Object System.DirectoryServices.ActiveDirectoryAccessRule $sid, 917684, 'Allow', $ObjectType, 'None', $InheritedObjectType
    $acl.AddAccessRule($ace)
    Set-ACL $TemplatePath -AclObject $acl

- name: Install PSPKI module
  community.windows.win_psmodule:
    name: PSPKI
    accept_license: true
    force: true
    state: present

- name: Set ACL for ESC7
  ansible.windows.win_shell: |
    Import-Module -Name PSPKI
    $ca = Get-CertificationAuthority
    $acl = Get-CertificationAuthorityAcl -CertificationAuthority $ca
    $newAcl = Add-CertificationAuthorityAcl -AclObject $acl `
              -Identity "Domain Users" `
              -AccessType "Allow" `
              -AccessMask "ManageCA,ManageCertificates,Enroll"
    Set-CertificationAuthorityAcl -InputObject $newAcl -RestartCA
