---
- hosts: pdc
  roles:
    - common
    - pdc
    - pdc_userdata
  gather_facts: no

- hosts: workstation
  roles:
    - workstation
  gather_facts: no


# - hosts: rdc
#   roles:
#     - rdc
#     - common

# - hosts: fileserver
#   roles:
#     - fileserver
#     - common

# - hosts: dhcpserver
#   roles:
#     - dhcpserver
#     - common
    